"""
Copilot Chart Router — serves saved Plotly JSON files by chart ID.
"""
import re

from fastapi import APIRouter, HTTPException, Depends
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from fastapi.responses import JSONResponse

from app.core.database import get_db
from app.modules.copilot.models import CopilotChart

chart_router = APIRouter(prefix="/copilot/charts", tags=["AI Copilot"])

_UUID_RE = re.compile(r"^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$")

@chart_router.get("/{chart_id}", summary="Fetch a saved Plotly chart by ID")
async def get_chart(chart_id: str, db: AsyncSession = Depends(get_db)):
    """
    Return the full Plotly figure JSON for a chart previously generated by the
    copilot agent, but fetched seamlessly from the `copilot_charts` PostgreSQL table.
    """
    if not _UUID_RE.match(chart_id):
        raise HTTPException(status_code=400, detail="Invalid chart ID format")

    result = await db.execute(select(CopilotChart).where(CopilotChart.id == chart_id))
    chart = result.scalar_one_or_none()
    
    if not chart:
        raise HTTPException(status_code=404, detail="Chart not found")

    return JSONResponse(content=chart.plotly_json)
